// <auto-generated />
namespace Assignment_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StreetNoMissing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StreetNoMissing));
        
        string IMigrationMetadata.Id
        {
            get { return "202207040115111_StreetNoMissing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
